import { useState } from 'react'

export default function ReasoningPanel({ reasoning, skillName, weakSubtopics }) {
  const [expanded, setExpanded] = useState(true)

  return (
    <div className="terminal-panel rounded p-4">
      {/* Header */}
      <div className="flex items-center justify-between mb-3">
        <div className="flex items-center gap-2">
          <span className="w-2 h-2 rounded-full bg-cyan-400 animate-pulse" style={{ boxShadow: '0 0 6px #00f5ff' }} />
          <span className="text-xs font-mono font-bold tracking-widest" style={{ color: '#00f5ff' }}>
            EXPLAINER_AGENT // {skillName?.toUpperCase()}
          </span>
        </div>
        <button onClick={() => setExpanded(!expanded)}
          className="text-gray-600 hover:text-cyan-400 transition-colors font-mono text-xs">
          {expanded ? '[COLLAPSE]' : '[EXPAND]'}
        </button>
      </div>

      {expanded && (
        <div className="space-y-3">
          {/* Reasoning text */}
          <div className="text-sm font-mono leading-relaxed" style={{ color: '#94a3b8' }}>
            <span style={{ color: 'rgba(0,245,255,0.4)' }}>{'> '}</span>
            {reasoning || 'Reasoning trace not available for this module.'}
          </div>

          {/* Weak subtopics */}
          {weakSubtopics?.length > 0 && (
            <div className="pt-2 border-t" style={{ borderColor: 'rgba(0,245,255,0.08)' }}>
              <p className="text-xs font-mono mb-2" style={{ color: '#fbbf24' }}>
                ⚠ WEAK SUBTOPICS DETECTED:
              </p>
              <div className="flex flex-wrap gap-1.5">
                {weakSubtopics.map(t => (
                  <span key={t} className="px-2 py-0.5 text-xs font-mono rounded"
                    style={{
                      background: 'rgba(251,191,36,0.08)',
                      color: '#fbbf24',
                      border: '1px solid rgba(251,191,36,0.25)',
                    }}>
                    {t}
                  </span>
                ))}
              </div>
            </div>
          )}

          {/* Footer */}
          <div className="text-xs font-mono" style={{ color: 'rgba(0,245,255,0.3)' }}>
            — Generated by Explainer Agent v2.4.1 · Parallelized via asyncio.gather
          </div>
        </div>
      )}
    </div>
  )
}
